language: node_js
cache:
  directories:
  - node_modules
install:
- bundle install
script:
- bundle exec jekyll build
branches:
  except:
  - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
env:
  global:
    secure: hvUlr/pOaRbfHjsxyCyb4rp80a7A4ZMrZjvytSRxMyZySuKpZBtGdoqMpb/FQM5NGjXhdvSSsrMfuF14LyVoKIuIf9Hs6s6zfIESQH5iIGngcbtsoQty+vX5swK0B8MMd4TgrjHg+k5RhwgGcyO3YPMCxGfclci+gJ1vSlp3usY=
